### ISSUE TITLE
Using workflows on Record actions

### ISSUE THREAD

**Issue by nosfas** [heloufir/filament-workflow-manager#1]
Hello.

I'm trying to add an action to the ViewResource and EditResource that would allow me to change the workflow status outside of the EditRecord.
I've managed to change it manually with this:
``
$this->record->workflow_status->workflow_status_id = $data['workflow_status_id'];
$this->record->workflow_status->save();
``
But this isn't clearly the intended way, since history isn't triggered.

Additionally.
Is there any way to use this plugin and disabling the workflow permissions?
Do you recommend any compatible user management? I've seen a few that don't see to be easily overridable to add the workflow permissions.

Thank you for this great plugin.

**Comment by heloufir** [comment]
Hello @nosfas 

Sorry for the late answer.
To make the edit in your `ViewResource` or `EditResource`, you can check this link [https://github.com/heloufir/filament-workflow-manager/blob/82ae46c368983f585abfd15e92f0751e7b4a9d04/src/Core/WorkflowResource.php#L10](https://github.com/heloufir/filament-workflow-manager/blob/82ae46c368983f585abfd15e92f0751e7b4a9d04/src/Core/WorkflowResource.php#L10)
This is the `save` function fired after you edit a record linked to a workflow, you can do the same logic in your custom function.

And to use the package without permissions, I will work on a new PR and link it to this issue.

**Comment by heloufir** [comment]
@nosfas You can use the version `1.1.10` of this package to use the `permission_enabled` flag on your configuration

[https://github.com/heloufir/filament-workflow-manager/blob/6b505af0e4cfb8055a56e5568bd57082ae2ea04f/config/filament-workflow-manager.php#L99](https://github.com/heloufir/filament-workflow-manager/blob/6b505af0e4cfb8055a56e5568bd57082ae2ea04f/config/filament-workflow-manager.php#L99)
