### ISSUE TITLE
Missing required parameters for id & model

### ISSUE THREAD

**Issue by hibuno** [heloufir/filament-workflow-manager#13]
Hi there,

I did a fresh install of this package by following the quickstart documentation, and then I saw a little bit of an error.

```Missing required parameters for [Route: filament.pages.workflow-history/{id}/{model}] [URI: admin/workflow-history/{id}/{model}] [Missing parameters: id, model].```

After, seeing your code I found the problem came from [this line](https://github.com/heloufir/filament-workflow-manager/blob/fd3627f7efe2a80d63d8263c2ad6652d8b07916e/src/Pages/WorkflowHistory.php#L26) a required parameter of id & model. And I think we need to make it optional like this ```workflow-history/{id?}/{model?}```. Cause when I try to change it into optional on the vendor directory, it works like a charm.

Thanks

**Comment by heloufir** [comment]
Hello @muhibbudins 
I will try to check this ASAP and let u know, sorry for the late answer.

**Comment by hibuno** [comment]
No problem, thanks in advance @heloufir
