### ISSUE TITLE
Adding tasks to each Workflow status

### ISSUE THREAD

**Issue by jigzstar** [heloufir/filament-workflow-manager#8]
I am new to filament admin.

However, I have a use case where I need to add a set of pre-created tasks or objectives for each workflow step or status.

What would be the best approach:
1 - Fork the repo, then add the related models, and migrations?
2 - Try to integrate it using new filament resources?

**Comment by heloufir** [comment]
Hello @jigzstar 

I didn't quite understand your need.
You need to create dynamically workflow statuses after your resource has been created? 

For example: I have a project resource linked to the workflow plugin, when a user create a project, dynamically a set of statuses are created after project, that's it?

**Comment by jigzstar** [comment]
Hi @heloufir,
Thanks for your response. Let me see if I can explain a bit better.

A little background:

I am using the plugin for applications submitted by users, that need to go through a couple departments before printing the required document. And each department has a checklist of items before they can pass it on to the next.

For example,
"Review Application" Status can have 

- [ ] Check that the user is not part of a company
- [ ] Check that All documents are valid 

Accounts Dept Review
- [ ] Debt analysis completed

... and so on

Makes sense?

**Comment by heloufir** [comment]
Hmm, so I think the plugin as is it can work correctly for you.
You need to configure the workflow for your model "Review, dept review, ...etc" then configure permissions to users so each user can access the statuses needed.

I don't think you need to configure something else.

**Comment by jigzstar** [comment]
Noted. I was thinking the same, just didn't want to be overkill

**Comment by heloufir** [comment]
Okey, I will close this issue, but if needed you can created or reopen it.
